# Generated by Django 2.1.5 on 2020-02-20 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20200220_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='print_pictures/')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PrintedObjects', to='accounts.UserProfile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='print',
            unique_together={('printer', 'name')},
        ),
    ]
