# Generated by Django 2.1.5 on 2020-02-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='print',
            unique_together=set(),
        ),
    ]
