# Generated by Django 2.1.5 on 2020-03-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='help_type',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('NEEDS', 'NEEDS'), ('OFFERS', 'OFFERS'), ('PRINTS', 'PRINTS')], default='SELECT', max_length=30),
        ),
    ]
