# Generated by Django 2.1.5 on 2020-02-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='file',
            field=models.ImageField(default='/profile_pictures/default.png', upload_to=''),
        ),
    ]
