# Generated by Django 2.1.5 on 2020-02-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200218_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='file',
            field=models.ImageField(default='/profile_pictures/default.png', upload_to='profile_pictures/'),
        ),
    ]
