# Generated by Django 2.1.5 on 2020-03-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_help_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='telegramUrl',
            field=models.TextField(blank=True),
        ),
    ]
