# Generated by Django 2.1.5 on 2020-01-23 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200123_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printed_object',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='printer',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='printed_object',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printed_objects', to='accounts.printer'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='accounts.userProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='printed_object',
            unique_together={('printer', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='printer',
            unique_together={('profile', 'name')},
        ),
    ]
