# Generated by Django 2.1.5 on 2020-01-23 15:04

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200123_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_organizer',
            new_name='owns_printer',
        ),
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.userProfile'),
        ),
    ]
