# Generated by Django 2.1.5 on 2020-02-15 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200124_1451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='printed_object',
            new_name='PrintedObject',
        ),
        migrations.AlterField(
            model_name='address',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='location',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='printedobject',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printed_objects', to='accounts.Printer'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='accounts.UserProfile'),
        ),
    ]
