# Generated by Django 2.1.5 on 2020-02-15 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200215_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='location',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='printedobject',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PrintedObjects', to='accounts.Printer'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='accounts.UserProfile'),
        ),
    ]
